# Generated by Django 4.2.11 on 2024-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fetchUser",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=26)),
                ("email", models.EmailField(max_length=26)),
                ("full_name", models.CharField(max_length=50)),
                ("phone_no", models.CharField(max_length=12)),
            ],
        ),
    ]
